name: CI/CD 

on:
  push:
    paths:
      - 'monitoring/prometheus.yml'
      - 'monitoring/docker-compose.yml'
    branches:
      - main

jobs:
  deploy-services:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Pull Latest Changes
      run: git pull origin main

    - name: Build and Push Prometheus Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/muslimapp-prometheus:latest ./monitoring
        docker push ${{ secrets.DOCKER_USERNAME }}/muslimapp-prometheus:latest

    - name: Deploy Updated Services
      run: |
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /path/to/project
          git pull origin main
          export MONGO_URI=${{ secrets.MONGO_URI }}
          docker-compose down prometheus
          docker-compose pull prometheus
          docker-compose up -d prometheus
        EOF
